/home/joker/Builds/cppamp_driver/build/compiler/bin/./clang++       \
-I/home/joker/Builds/cppamp_driver/src/utils -I/usr/include/CL/../  \
-DGTEST_HAS_TR1_TUPLE=0 -stdlib=libc++ -std=c++amp                  \
-I/home/joker/Builds/cppamp_driver/src/include                      \
-I/home/joker/Builds/cppamp_driver/src/libc++/libcxx/include        \
-std=c++amp -std=c++amp                                             \       
-L/home/joker/Builds/cppamp_driver/build/build/Release/lib          \
-L/home/joker/Builds/cppamp_driver/build/libc++/libcxx/lib          \
-L/home/joker/Builds/cppamp_driver/build/libc++/libcxxrt/lib        \
-Wl,--rpath=/home/joker/Builds/cppamp_driver/build/build/Release/lib:/home/joker/Builds/cppamp_driver/build/libc++/libcxx/lib:/home/joker/Builds/cppamp_driver/build/libc++/libcxxrt/lib -lc++ -lcxxrt -ldl -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive  \ 
-lpthread                                                           \
BlackScholes.cpp -o black_scholes 
	
